remote_theme: pages-themes/cayman@v0.2.0   # or: slate, minimal, hacker, leap-day
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

defaults:
  - scope:
      path: "probability"
    values:
      layout: default
      math: true
  - scope:
      path: "research"
    values:
      layout: default
  - scope:
      path: "fiction"
    values:
      layout: default
